print("first line\n")
print("second line\n")
print("fourth line\n")
print("fifth line\n")
print("six line\n")
print("seven line\n")
print("eight line\n")
print("nine line\n")
print("ten line\n")
print("elven line\n")
print("twelve line\n")
print("fdfd")